# Generated by Django 4.2.2 on 2023-06-10 22:05

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, verbose_name='👤 Username')),
                ('nickname', models.CharField(help_text='Nickname should be unique', max_length=32, unique=True, verbose_name='👤 Nickname')),
                ('email', models.EmailField(help_text='Email should be unique', max_length=32, unique=True, verbose_name='📬 Email')),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='🥳 Birth date')),
                ('account_photo', models.ImageField(blank=True, null=True, upload_to=account.models.username_photo_path, verbose_name='🖼 Change account photo')),
                ('account_banner', models.ImageField(blank=True, null=True, upload_to=account.models.username_photo_path, verbose_name='Change account banner')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='🏡 City')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='🏙 Country')),
                ('changed_nickname', models.DateTimeField(default=django.utils.timezone.now, help_text='Nickname can be changed every 24 hours', verbose_name='Changed nickname date')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Is verified account ☑️')),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribers', models.ManyToManyField(blank=True, null=True, related_name='subscribers_set', to='account.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
