# Generated by Django 4.2.2 on 2023-07-08 10:30

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, verbose_name='👤 Username')),
                ('nickname', models.CharField(help_text='Nickname should be unique', max_length=32, unique=True, verbose_name='👤 Nickname')),
                ('email', models.EmailField(help_text='Email should be unique', max_length=32, unique=True, verbose_name='📬 Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='🥳 Birth date')),
                ('account_photo', models.ImageField(blank=True, null=True, upload_to=account.models.username_photo_path, verbose_name='🖼 Change account photo')),
                ('account_banner', models.ImageField(blank=True, null=True, upload_to=account.models.username_banner_path, verbose_name='Change account banner')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='🏡 City')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='🏙 Country')),
                ('biography', models.TextField(blank=True, max_length=256, null=True, verbose_name='🏙 Biography')),
                ('changed_nickname', models.DateTimeField(default=django.utils.timezone.now, help_text='Nickname can be changed every 24 hours', verbose_name='Changed nickname date')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Is verified account ☑️')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='⛔️ Is account blocked')),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_accounts', models.ManyToManyField(blank=True, null=True, related_name='blocked_accounts_set', to=settings.AUTH_USER_MODEL, verbose_name='Blocked accounts')),
                ('subscribers', models.ManyToManyField(blank=True, null=True, related_name='subscribers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, null=True)),
                ('code', models.CharField(max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
