# Generated by Django 4.2.2 on 2023-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='links',
        ),
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='🏙 Biography'),
        ),
    ]
