# Generated by Django 4.2.2 on 2023-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField()),
                ('code', models.CharField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
