# Generated by Django 4.2.2 on 2023-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_slug'),
        ('account', '0002_verifiedaccount_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='posts_set', to='post.post'),
        ),
    ]
