# Generated by Django 4.2.2 on 2023-07-22 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_blocked_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
