# Generated by Django 4.2.2 on 2023-07-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photo.photo', verbose_name='Фотографії'),
        ),
    ]
