# Generated by Django 4.2.2 on 2023-07-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
    ]
