# Generated by Django 4.2.2 on 2023-07-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_reply',
        ),
    ]
