# Generated by Django 4.2.2 on 2023-07-27 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_is_pinned_post_unique_is_pinned'),
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='post.post'),
        ),
    ]
