# Generated by Django 4.2.2 on 2023-07-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0001_initial'),
        ('post', '0004_alter_post_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600, verbose_name='Вміст коментарю')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Коментар було редаговано')),
                ('device', models.CharField(max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_comment_set', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='photo.photo', verbose_name='Фотографії')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_comment_set', to='comment.comment')),
            ],
        ),
    ]
